- name: Web Deployment Playbook
  hosts: TESTENV
  tasks: 
  - name: Install Apache
    yum:
      name: httpd
      state: present
  - name: Copy HTML
    copy:
      src: index.html
      dest: /var/www/html
  - name: Start Apache Service
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: yes
